#ifndef MAIN_H
#define MAIN_H

//PROGRAMME: programme testeServiceBaseDeTemps
//DESCRIPTION:Programme qui teste le fonctionnement du module serviceBaseDeTemps en faisant clignoter une DEL
//HISTORIQUE:
// 2020-11-13, Yves Roy: creation

//inclusions globales
#include <arduino.h>

//DEFINITIONS REQUISES PAR LE MODULE:
//Dependances materielles:
//pas de dependances materielles

//Dependances logicielles:
#define PILOTETICKER_PERIODE_EN_MS 1.0
//#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES 1


#define VERSION_MAJEUR          1
#define VERSION_MINEUR  	3

#define INTERFACEB1_VALEUR_LUE_SI_APPUYE  0   
#define INTERFACEB1_VALEUR_LUE_SI_RELACHE 1
#define INTERFACEB1_DELAI_ANTI_REBOND_EN_MS  15
#define INTERFACET1_VALEUR_POUR_ALLUMER  0   
#define INTERFACET1_VALEUR_POUR_ETEINDRE 1

#define INTERFACEB2_VALEUR_LUE_SI_APPUYE  1   
#define INTERFACEB2_VALEUR_LUE_SI_RELACHE 0



#define INTERFACEB3_VALEUR_LUE_SI_APPUYE  1   
#define INTERFACEB3_VALEUR_LUE_SI_RELACHE 0




//Dépendances logicielles:
#define FREQUENCE_DE_LA_BASE_DE_TEMPS_EN_HZ 2000.0
#define PILOTETIMER1MODE2_TAUX_DE_BITS 19200.0
#define PILOTETIMER1MODE2_UTILISE_LE_DOUBLEUR_DE_TAUX  1
#define INTERFACEB1_FREQUENCE_DES_LECTURES_EN_HZ  100.0
#define INTERFACEB3_FREQUENCE_DES_LECTURES_EN_HZ  100.0
#define INTERFACEB2_FREQUENCE_DES_LECTURES_EN_HZ  100.0
#define INTERFACEB1_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION 10
#define INTERFACEB2_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION 10
#define INTERFACEB3_NOMBRE_MINIMUM_DE_LECTURES_PAR_DECISION 10
#define PROCESSUSCLIGNOTANT_TEMPS_ALLUME_EN_MS  500.0
#define PROCESSUSCLIGNOTANT_PERIODE_EN_MS 1000.0

#define SERVICEBASEDETEMPS_NOMBRE_DE_PHASES 5 

#define MAIN_TEST_PHASE 0
#define SERVICEPROTOCOLE637_PHASE_TRANSMISSION 1
#define SERVICEPROTOCOLE637_PHASE_RECEPTION 2
#define INTERFACESTM_PHASE_RECEPTION 3
#define INTERFACESTM_PHASE_TRANSMISSION 4


#define SERVICEPROTOCOLE637_FREQUENCE_MAXIMALE_DES_TRANSMISSIONS_EN_HZ 500.0
#define SERVICEPROTOCOLE637_NOMBRE_DE_DONNEES_MAXIMUM  16
#define SERVICEPROTOCOLE637_DEBUT_DE_TRAME  '$'
#define SERVICEPROTOCOLE637_INSERTION 0x00
#define SERVICEPROTOCOLE637_TEMPS_D_ATTENTE_MAXIMAL_EN_MS 4
#define SERVICEPROTOCOLE637_FREQUENCE_MAXIMALE_DES_LECTURES_EN_HZ 2000.0

//INFORMATION PUBLIQUE:
//Definitions publiques:
#define INFORMATION_DISPONIBLE  1
#define INFORMATION_TRAITEE  0
#define REQUETE_ACTIVE  1
#define REQUETE_TRAITEE 0
#define MODULE_EN_FONCTION 1
#define MODULE_PAS_EN_FONCTION 0


//Fonctions publiques:
void neFaitRien(void);

//Variables publiques:
//pas de variables publiques
#endif

